[package]
name = "testprog"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "testprog"
path = "main.rs"

[dependencies]
vulkano = { version = "0.34.0", features = ["macros"] }
vulkano-shaders = "0.34.0"
vulkano-util = "0.34.0"
winit = { version = "0.28", features = ["x11", "wayland"] }
bytemuck = { version = "1.13", features = ["derive"] }
glam = "0.24"
memoffset = "0.9"
